// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using QuickAutomatorService.Models;

namespace QuickAutomatorService.Data
{
    public partial class DautomateContext : DbContext
    {
        public DautomateContext()
        {
        }

        public DautomateContext(DbContextOptions<DautomateContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ConfigParam> ConfigParams { get; set; }
        public virtual DbSet<Quick> Quicks { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ConfigParam>(entity =>
            {
                entity.Property(e => e.ConfigKey).IsFixedLength();
            });

            modelBuilder.Entity<Quick>(entity =>
            {
                entity.Property(e => e.DateUploaded).HasComment("date on which data was uploaded");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        #region DbConfig

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            builder.UseSqlServer(@"Data Source=DESKTOP-AHTKNDP\ITWORKS;Initial Catalog=DAutomate;User ID=sa;Password=excalibur@33;TrustServerCertificate=True");
        }

        #endregion

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}