// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuickAutomatorService.Models
{
    public partial class ConfigParam
    {
        [Key]
        [StringLength(30)]
        [Unicode(false)]
        public string ConfigKey { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string ConfigValue { get; set; }
    }
}