// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuickAutomatorService.Models
{
    [Table("Quick")]
    public partial class Quick
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string BranchCode { get; set; }
        [Column("CIF")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cif { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Acct { get; set; }
        [Column("KYCStatus")]
        [StringLength(50)]
        [Unicode(false)]
        public string Kycstatus { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string Fullname { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Telephone { get; set; }
        public int? MonthsLastDeposit { get; set; }
        public int? AgeClient { get; set; }
        public int? AgeAcc { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? AvgDepositIn3Months { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? AvgWithdrawalIn3Months { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? LoanAmt { get; set; }
        public int? Cycle { get; set; }
        public int? AvgDaysIn12Months { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string BlackList { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? AvgNumDepositIn3Months { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? AvgNumWithdrawnIn3Months { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Gender { get; set; }
        public int? TotalNumDep { get; set; }
        public int? TotalNumWithdraw { get; set; }
        public int? IsStaff { get; set; }
        [Column("DPD")]
        [StringLength(100)]
        [Unicode(false)]
        public string Dpd { get; set; }
        public int? IsLoanClient { get; set; }
        /// <summary>
        /// date on which data was uploaded
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? DateUploaded { get; set; }
    }
}